### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by corestone**
Library version update!

### CODE REVIEW

**Comment by AkaZver** [comment]
Hello, @corestone !
Thank you for your PR :)

Can you update version of lombok-plugin to 6.6.3 in `plugins` and `dependencies` sections of `build.gradle`?
We need it because this version of plugin uses lombok 1.18.26: https://github.com/freefair/gradle-plugins/blob/6.6.3/lombok-plugin/build.gradle#L9
Without this change we can't guarantee test integrity

**Comment by corestone** [comment]
Yes, Lombok version update

**Comment by AkaZver** [comment]
Failed sonarqube task is a problem with my CI/CD settings here: https://github.com/AkaZver/mapstruct-plugin/blob/master/.github/workflows/main.yml#L6

I will fix it in the next PR

**Comment by AkaZver** [comment]
@corestone, version 1.0.5 was published

**Pull request merged**
